### ISSUE TITLE
factory example is not complete

### ISSUE THREAD

**Issue by dohomi** [rwwagner90/angular-styleguide-es6#10]
Hello,

I think this snipped out of your docs doesn't work at all:

``` javascript

/* recommended */

// dataservice factory
angular
    .module('app.core')
    .factory('dataservice', dataservice);

class dataservice { 
  constructor($http, logger) {
    this.$http = $http;
    this.logger = logger;
  }
  getAvengers() {
    return this.$http.get('/api/maa')
      .then(getAvengersComplete)
      .catch(getAvengersFailed);

    getAvengersComplete(response) => {
      return response.data.results;
    }

    getAvengersFailed(error) => {
      this.logger.error('XHR Failed for getAvengers.' + error.data);
    }
  }
}

```

A service is not able to take a class constructor. I used `.factory('dataservice',() => new dataservice())` but then `this.$http`would be undefined...
Any idea how to solve this?
Cheers

**Comment by RobbieTheWagner** [comment]
@dohomi would you mind setting up an example project for me to take a look at? It's definitely possible that some of the code on the guide does not quite work.

**Comment by dohomi** [comment]
@rwwagner90 I'll try to free some time on the weekend. Currently I stick to the non-es6 guide for the factories/services. As factories are function calls I think a class does not make fully sense - at least some additional lines of code needs to get included making this functional

**Comment by fesor** [comment]
> Any idea how to solve this?

Actually:

``` javascript
angular
    .module('app.core')
    .factory('dataservice', ($http, logger) => new dataservice($http, logger))
```

But in this particular example it would be better to use `.service` since we don't have factories:

``` javascript
angular
    .module('app.core')
    .service('dataservice', dataservice)
```

Factories should not be used that much. Most of devs used factories to encapsulated implementation details of their objects:

``` javascript
function dataserviceFactory($http, logger) {

     return {
         getAvengers() {
             return this.$http.get('/api/maa')
                .then(
                      response => response.data.results,
                      reason => {
                            logger.error('XHR Failed for getAvengers.' + reason.data)
                      }
                )
         }
     }
}
```

But if you don't mind `$http` and `logger` to be public properties, you can just define it as object with type `DataService`.

**Comment by RobbieTheWagner** [comment]
@fesor I agree. I never use factories personally. It was one of the example on the guide though, so I attempted to implement it in ES6. If you have the time, and wanted to look over the guide and create a PR to address possible improvements, that would be great!

**Comment by mikeerickson** [comment]
@fesor @rwwagner90 

FWIW, while I do agree that a service should be used in this (and really all cases with ES6 Angular), they can still be used by applying the following syntax

```
angular.module('app.core')
    .factory('dataservice', ['$http', 'logger', ($http, logger) => new dataservice($http, logger)]);
```

I will update style guide to include this format, as well as provide additional description, etc. that while factories can be used, it would be better served to stick with using services for Angular & ES6 moving forward.
