### ISSUE TITLE
Component guide 

### ISSUE THREAD

**Issue by mikeerickson** [rwwagner90/angular-styleguide-es6#13]
Nice abstraction of original guide to ES6 format.  

How about including a section for Angular Components (those introduced in 1.5)

I have a nice abstraction convention myself, but would be curious how it compares to others.

**Comment by RobbieTheWagner** [comment]
Hi @mikeerickson that sounds like a great idea to me! Would you be interested in submitting a PR to add it?

**Comment by mikeerickson** [comment]
@rwwagner90 sure thing, give me a couple days

**Comment by RobbieTheWagner** [comment]
Awesome. Just let me know when you have something for me to review @mikeerickson. I'm definitely trying to strive for making this a community driven guide, so PRs are always welcome!

**Comment by RobbieTheWagner** [comment]
Any luck @mikeerickson?

**Comment by mikeerickson** [comment]
Sorry about that, got swamped at work and have been craming like crazy for a new release we have coming out on Friday.  I will nail it down ASAP though.  Did create some framework for it, but need to wrap it up nicely :-)

Also, I am thinking of adding some tests (mocha) for the Component section, but that can come "later" so that the rest of the SG can be updated to contain tests as well (thoughts)

**Comment by mikeerickson** [comment]
@rwwagner90 Hey bud, can you give me a good contact email?  I want to discuss a couple things with you.  Thx :-)

**Comment by RobbieTheWagner** [comment]
@mikeerickson seems that Todd Motto has updated his guide to ES2015, might be a good idea to go through and pull in some of his stuff https://github.com/toddmotto/angular-styleguide

**Comment by mikeerickson** [comment]
@rwwagner90 Thanks, I shall have a look :-)
