### ISSUE TITLE
non-working "reccomended" example

### ISSUE THREAD

**Issue by zachlysobey** [rwwagner90/angular-styleguide-es6#2]
[y022](https://github.com/rwwagner90/angular-styleguide-es6#style-y022)

```
/* recommended */
angular
    .module('app')
    .controller('SomeController', SomeController);

class SomeController {
  constructor() { }
}
```

ES6 classes are not hoisted as I understand it, and as such, this example will not work. SomeController will not be defined here before it is used.

**Comment by RobbieTheWagner** [comment]
@zachlysobey the point of this rule is as it states "When using a module, avoid using a variable and instead use chaining with the getter syntax.".

You are expected to define your classes wherever is valid.

This is just saying to avoid doing:

`let app = angular.module('app');`

And to just chain stuff like:

```
angular
    .module('app')
    .controller('SomeController', SomeController);
```

For the purposes of the example, the class isn't even really necessary to get the gist of it.

**Comment by zachlysobey** [comment]
I get the point of the example and all... but I still don't think its good to put code examples that would fail when pasted verbatim. Even just putting a comment like `// SomeController.js` would be better IMO.

**Comment by zachlysobey** [comment]
Really, in an es6 styleguide, I think you _need_ to touch upon how the (es6) modules are loaded up front.

**Comment by RobbieTheWagner** [comment]
@zachlysobey I agree with you. The guide could certainly use some improvements. I just took a first pass at converting the original guide to ES6. I'd definitely like to work with you and others who are interested to make it better. Would you like to propose some edits and put up a PR?

**Comment by zachlysobey** [comment]
I'd love to make some PR's, not sure if/when I'll get to it though.

Got a big Open Source TODO list and not enough time in the day ;-)

**Comment by RobbieTheWagner** [comment]
Totally understandable @zachlysobey. I'd say just start small. Every little bit helps :smile:

**Comment by zachlysobey** [comment]
P.S. didn't mean to come off as too critical above. I think its great that you put the effort in to do this, and I hope that we can all work together to make it worthy of the repo it forked from.

**Comment by RobbieTheWagner** [comment]
@zachlysobey that's my hope as well. There is a serious need for a good ES2015 style guide. I'll definitely need community help to get it in ship shape though.

**Comment by RobbieTheWagner** [comment]
@zachlysobey aside from the desire to have all examples either work copied and pasted or have comments denoting that snippets are in different files, is there anything else you'd like me to take a pass at? I know you're busy and don't necessarily have time to work on this and submit a PR, but I'd like to handle the issues you see.

**Comment by zachlysobey** [comment]
yea, sorry I still really need to read this end-to-end.

The comments would sufficiently "fix" this issue I think.

As far as my recommendations moving forward? I think it's a good idea to prominently feature tooling and discussion of es6 modules and module loaders (if not more opinionated recommendation of one specific tool-chain).

I have mixed feelings as to whether thats "in scope" for a style-guide, but in this case I think there is a lot of value in actually helping someone set up angular for use with es6 modules, etc...

In my angular projects, I've used es6 extensively, but mostly just as sugar (const/let/destructuring/default-params/template-strings). To me the tough part has always been how the module set up should work.

Another small note:

`let vm = this;` IMO isn't necessary anymore. I think its easy enough just to put things on `this` without changing _context_ within controllers now that we have es6 fat arrows.

Sorry to just dump all this in this issue. Feel free to make new ones for any of these topics and @mention me and I'll be happy to discuss further.

**Comment by RobbieTheWagner** [comment]
@zachlysobey this style guide was mostly written with [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular) in mind. It's what I usually use for my ES6 Angular projects. We could make it agnostic though and just explain various ways to set up modules. I'm open to suggestions.

I started making some fixes for the issues we discussed. More will be coming as I have more time. I'd still appreciate any help you could offer with PRs. Even just improving one example every so often or something would be helpful. If every person that reads this guide just improved a few lines, we'd start to have a really nice guide here.

**Comment by mikeerickson** [comment]
@zachlysobey @rwwagner90 

Hey guys, I am in the process of reviewing the current release of guide and addressing issues such as this (I have yet to find one that still exists thus far).

I believe this specific item has already been addressed, thus I am keen to close up this ticket?

**Comment by zachlysobey** [comment]
@mikeerickson I regret to say I'm not gonna be working on this (haven't been doing angular for one). So don't keep open on my account. Good luck with the project though guys!

**Comment by RobbieTheWagner** [comment]
Closing, since no one seems to be in favor of keeping open
